package com.justin.id_34279075.nutritrack.data.patient

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a patient class. It contains the most comprehensive information of a patient.
 * The table name created is "patients".
 */
@Entity(tableName = "Patient")
data class Patient(

    /**
     * Assume here that each userID provided is already unique, therefore eliminating the need
     * for a unique identifier to be generated by Room (e.g. by setting autoGenerate=true).
     */
    @PrimaryKey
    val userID: String,

    val phoneNumber: String,

    /**
     * Password may be null as the owner of the userID might not register yet.
     */
    val password: String? = null,

    /**
     * Name may be null also since the owner of the userID might not register yet.
     */
    val name: String? = null,

    val sex: String,

    val vegetableScore: Float,

    val fruitsScore: Float,

    val grainsAndCerealScore: Float,

    val wholeGrainsScore: Float,

    val meatAndAlternativesScore: Float,

    val dairyScore: Float,

    val waterScore: Float,

    val saturatedFatScore: Float,

    val unsaturatedFatScore: Float,

    val sodiumScore: Float,

    val sugarScore: Float,

    val alcoholScore: Float,

    val discretionaryFoodsScore: Float,

    val totalHEIFAScore: Float,

    val fruitServeSize: Float,

    val fruitVariationScore: Float,

)